import React, { useEffect, useRef, useState } from 'react';
import {PcFeatures,usePcStatus} from './PcFeatures.jsx';
import { Folder, Clock, FileText, DownloadSimple, Desktop, Image, MusicNotes, FilmStrip, HardDrive, Globe, ArrowLeft, CaretRight, MagnifyingGlass, Minus, Square, X, Sparkle, ShieldCheck, DotsThree, ArrowUp, SquaresFour, CalendarBlank, GearSix, WifiHigh, SpeakerHigh, BatteryFull, Check, ArrowCounterClockwise, Lock, Buildings, User, Monitor, FilePdf, Table } from '@phosphor-icons/react';

const personalFiles = [
 {id:'proposal',name:'项目方案.docx',type:'doc',kind:'Word 文档',size:'2.4 MB',modified:'2026年9月28日 14:20',folder:'工作/2026年Q4项目',title:'项目目标',lines:[['项目目标','在 2026 年第四季度完成核心功能上线，提升业务效率与用户体验。'],['主要任务','完成产品开发、测试与上线准备，同时推进培训和试用反馈收集。'],['计划安排','10 月启动开发与资源协调，11 月开展测试，12 月完成首批试用。']],excerpt:'在 2026 年 Q4 完成核心功能上线，10 月开发、11 月测试、12 月试用。'},
 {id:'minutes',name:'会议纪要.pdf',type:'pdf',kind:'PDF 文档',size:'1.1 MB',modified:'2026年9月26日 10:08',folder:'工作/2026年Q4项目',title:'主要任务',lines:[['会议结论','先验证资料检索与文档摘要，再邀请首批用户试用。所有文档均为原型示例资料。'],['任务分工','陈晨负责方案初稿，李宁负责预算核对，王敏负责汇总评审意见。'],['下一步','10 月 9 日完成方案初稿，10 月 10 日核对预算，10 月 12 日提交评审意见。']],excerpt:'先验证资料检索与摘要；陈晨、李宁、王敏分别推进方案、预算和评审。'},
 {id:'budget',name:'预算明细.xlsx',type:'sheet',kind:'Excel 工作表',size:'846 KB',modified:'2026年9月25日 16:33',folder:'工作/2026年Q4项目',title:'预算安排',lines:[['预算总额','120 万元。此数字仅用于交互演示，不代表本系统的研发报价。'],['费用构成','产品研发 70 万元；测试与设备 25 万元；培训与试用 15 万元；预备费用 10 万元。'],['执行要求','各项费用由项目负责人核对，实际使用前完成审批。']],excerpt:'演示预算合计 120 万元，包含研发、测试设备、培训与预备费用。'}
];
const orgFiles = [
 {id:'policy',name:'设备借用流程.pdf',type:'pdf',kind:'PDF 文档',size:'420 KB',modified:'2026年9月30日 09:00',folder:'单位知识库/办公资源',title:'设备借用',lines:[['适用范围','在岗人员临时借用办公设备。本文为组织场景的示例制度。'],['办理步骤','提交申请，填写设备名称、用途与使用时间；由部门负责人确认；到行政管理部门领取并签字。'],['归还要求','使用完毕后按约定归还，发现设备损坏时联系行政管理部门。']],excerpt:'提交申请 → 部门确认 → 设备领取；使用完毕后按约定归还。'},
 {id:'meeting',name:'会议室使用说明.docx',type:'doc',kind:'Word 文档',size:'680 KB',modified:'2026年9月29日 15:30',folder:'单位知识库/办公资源',title:'会议准备',lines:[['预约规则','使用单位的预约入口选择会议室和时段。此入口在原型中不连接实际系统。'],['设备准备','提前检查投影、音频与网络，借用额外设备时按设备借用流程办理。'],['结束检查','离开时关闭设备、带走个人资料并恢复座位。']],excerpt:'提前预约并检查会议设备；额外设备按借用流程办理。'}
];
const navItems=[['files','我的文件',Folder],['recent','最近使用',Clock],['documents','文档',FileText],['downloads','下载',DownloadSimple],['desktop','桌面',Desktop],['pictures','图片',Image],['music','音乐',MusicNotes],['videos','视频',FilmStrip],['archive','已归档',Folder],['disk','本机文件',HardDrive],['network','网络位置',Globe]];
const destinations={doc:'方案文档',pdf:'参考资料',sheet:'预算表格'};
function FileIcon({file}){const Icon={doc:FileText,pdf:FilePdf,sheet:Table}[file.type];return <span className={'file-kind '+file.type}><Icon size={28} weight="fill"/></span>;}

export function App(){
 const [space,setSpace]=useState('personal'),[files,setFiles]=useState(personalFiles),[selected,setSelected]=useState(personalFiles.map(f=>f.id)),[nav,setNav]=useState('files'),[query,setQuery]=useState(''),[prompt,setPrompt]=useState(''),[task,setTask]=useState('summary'),[summaryIds,setSummaryIds]=useState(personalFiles.map(f=>f.id)),[modal,setModal]=useState(null),[source,setSource]=useState(null),[launcher,setLauncher]=useState(false),[toast,setToast]=useState(''),[undo,setUndo]=useState(null),[model,setModel]=useState('local'),[fileOpen,setFileOpen]=useState(true),[aiOpen,setAiOpen]=useState(true),[maximized,setMaximized]=useState(false),[busy,setBusy]=useState(false),[chat,setChat]=useState('整理这三份资料，生成工作摘要。'),[notice,setNotice]=useState('');
 const [pc,setPc,refreshPc]=usePcStatus();
 const [now,setNow]=useState(new Date());
 useEffect(()=>{const timer=setInterval(()=>setNow(new Date()),60000);return()=>clearInterval(timer);},[]);
 const modalRef=useRef(null),toastTimer=useRef(null),actionTimer=useRef(null);
 const selectedFiles=files.filter(f=>selected.includes(f.id)),summaries=files.filter(f=>summaryIds.includes(f.id)),org=space==='org';
 const visible=files.filter(f=>nav==='archive'?f.archived:['files','recent','documents','disk'].includes(nav)?!f.archived:false).filter(f=>[f.name,f.excerpt].some(v=>v.toLowerCase().includes(query.toLowerCase())));
 function flash(text){setToast(text);clearTimeout(toastTimer.current);toastTimer.current=setTimeout(()=>setToast(''),4000);}
 function changeSpace(value){if(value===space)return;clearTimeout(actionTimer.current);const next=value==='org'?orgFiles:personalFiles;setSpace(value);setFiles(next);setSelected(next.map(f=>f.id));setSummaryIds(next.map(f=>f.id));setNav('files');setQuery('');setTask('summary');setUndo(null);setModel(value==='org'?'intranet':'local');setChat(value==='org'?'借用会议设备需要哪些步骤？':'整理这三份资料，生成工作摘要。');setBusy(false);setNotice('');setModal(null);setSource(null);flash('已切换演示视角；正式产品由账户与设备策略决定。');}
 function toggle(id){setSelected(p=>p.includes(id)?p.filter(x=>x!==id):[...p,id]);}
 function openSource(file){setSource(file);setModal('source');}
 function generate(){if(!selectedFiles.length){flash('请先勾选至少一份资料。');return;}setBusy(true);setNotice('');actionTimer.current=setTimeout(()=>{setSummaryIds([...selected]);setTask('summary');setChat('整理选中的 '+selected.length+' 份资料，生成工作摘要。');setBusy(false);flash('示例摘要已更新，可查看原文核对。');},500);}
 function organize(){if(org){flash('单位知识库为只读资料；请联系资料管理员。');return;}if(!selectedFiles.length){flash('请先勾选要整理的文件。');return;}if(selectedFiles.some(f=>f.archived)){flash('所选文件已归档，可先撤销上一次整理。');return;}setTask('organize');setChat('把选中的文件按类型整理到项目归档。');setNotice('');}
 function commitPlan(){const snapshot=files.map(f=>({...f})),affected=selectedFiles.map(f=>f.id);setFiles(p=>p.map(f=>affected.includes(f.id)?{...f,archived:true,folder:'项目归档/'+destinations[f.type]}:f));setUndo({files:snapshot,ids:affected});setModal(null);setNav('archive');setTask('done');setQuery('');flash('已在原型中整理 '+affected.length+' 个示例文件。');}
 function undoPlan(){if(!undo)return;setFiles(undo.files);setSelected(undo.ids);setUndo(null);setNav('files');setTask('summary');flash('已恢复上一次整理前的示例文件位置。');}
 function submitPrompt(e){e.preventDefault();const value=prompt.trim();if(!value)return;setChat(value);setPrompt('');setNotice('');if(/整理|归档|分类/.test(value)&&!/摘要|总结/.test(value)){organize();return;}if(/摘要|总结|汇总|概括/.test(value)){generate();return;}if(/找|搜索|预算|借用|设备/.test(value)){const word=/预算/.test(value)?'预算':/设备|借用/.test(value)?'设备':value.replace(/帮我|找出|找到|查找|搜索|文件|资料|一下|请|找|的/g,'').trim();setQuery(word);setNav('files');setFileOpen(true);setTask('search');setNotice('已在示例文件名和内容中搜索“'+word+'”。');return;}setNotice('这是交互原型，尚未连接模型。可以试试“生成摘要”“整理文件”或“找预算文件”。');}
 function goNav(id){setNav(id);setQuery('');setFileOpen(true);setLauncher(false);}
 function launch(app){setLauncher(false);if(app==='文件'){setFileOpen(true);return;}if(app==='AI 助手'){setAiOpen(v=>!v);return;}if(app==='系统设置'){setModal('settings');return;}if(app==='浏览器'){setModal('browser');return;}setModal('app:'+app);}
 useEffect(()=>()=>{clearTimeout(toastTimer.current);clearTimeout(actionTimer.current);},[]);
 useEffect(()=>{if(!modal)return;const previous=document.activeElement;requestAnimationFrame(()=>modalRef.current?.querySelector('button,input,select')?.focus());function key(e){if(e.key==='Escape')setModal(null);if(e.key==='Tab'){const els=[...modalRef.current.querySelectorAll('button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea')],first=els[0],last=els.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}}window.addEventListener('keydown',key);return()=>{window.removeEventListener('keydown',key);previous?.focus();};},[modal]);
 const titles={browser:'网页浏览器',audio:'音量设置',network:'网络设置',power:'电池与电源',summary:'工作摘要 · 示例结果',source:source?.name,plan:'确认文件整理',settings:'系统设置',apps:'应用中心'};
 return <main className="desktop-shell">
 <div className="demo-bar"><span><img className="brand-logo brand-logo-small" src="/lantu-os-logo.png" alt=""/> <strong>澜图 OS</strong> <span className="demo-note">{pc.native?'系统控制已连接 · AI 结果为示例':'交互原型 · 示例文件与 AI 结果'}</span></span><div className="segmented-control" aria-label="演示视角"><button aria-pressed={!org} onClick={()=>changeSpace('personal')}><User size={14}/>个人空间</button><button aria-pressed={org} onClick={()=>changeSpace('org')}><Buildings size={14}/>单位空间</button></div></div>
 <div className={'workspace '+(!fileOpen||!aiOpen?'single-window ':'')+(maximized?'maximized':'')}>
 {fileOpen&&<section className="file-window" aria-label="文件管理器"><header className="window-title"><Folder weight="fill" size={25} color="#168bff"/><strong>{org?'单位资料':'我的文件'}</strong><div className="window-actions"><button aria-label="最小化文件窗口" onClick={()=>setFileOpen(false)}><Minus/></button><button aria-label="切换窗口大小" onClick={()=>setMaximized(!maximized)}><Square/></button><button aria-label="关闭文件窗口" onClick={()=>setFileOpen(false)}><X/></button></div></header>
 <div className="file-body"><nav className="sidebar" aria-label="文件位置">{navItems.map(([id,label,Icon],i)=><React.Fragment key={id}>{i===4&&<div className="sidebar-label">常用位置</div>}{i===9&&<div className="sidebar-label">此电脑</div>}<button className={'nav-item '+(nav===id?'active':'')} onClick={()=>goNav(id)} aria-current={nav===id?'page':undefined}><Icon size={21} weight={id==='files'?'fill':'regular'}/><span>{org&&id==='files'?'单位资料':label}</span></button></React.Fragment>)}</nav>
 <div className="file-content"><div className="file-toolbar"><button className="icon-button" aria-label="返回项目目录" onClick={()=>goNav('files')}><ArrowLeft size={19}/></button><div className="breadcrumb">{org?'单位知识库':'我的文件'}<CaretRight size={12}/><span>{nav==='archive'?'项目归档':org?'办公资源':'2026年Q4项目'}</span></div><label className="search-wrap"><MagnifyingGlass size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索文件或内容" aria-label="搜索文件或内容"/>{query&&<button onClick={()=>setQuery('')} aria-label="清除搜索"><X size={13}/></button>}</label></div>
 <div className="selection-toolbar"><label><input type="checkbox" checked={visible.length>0&&visible.every(f=>selected.includes(f.id))} onChange={e=>setSelected(e.target.checked?[...new Set([...selected,...visible.map(f=>f.id)])]:selected.filter(id=>!visible.some(f=>f.id===id)))}/>选择文件</label><span>已选 {selectedFiles.length} 项</span><button className="text-button" onClick={generate} disabled={busy||!selectedFiles.length}>生成摘要</button></div>
 <div className="file-table-wrap"><table className="file-table"><thead><tr><th>名称</th><th className="optional-column">修改日期</th><th className="optional-column">类型</th><th className="size-column">大小</th></tr></thead><tbody>{visible.map(f=><tr key={f.id} className={'file-row '+(selected.includes(f.id)?'selected':'')}><td><div className="file-name"><input type="checkbox" aria-label={'选择'+f.name} checked={selected.includes(f.id)} onChange={()=>toggle(f.id)}/><FileIcon file={f}/><button onClick={()=>openSource(f)}>{f.name}</button></div></td><td className="optional-column">{f.modified}</td><td className="optional-column">{f.kind}</td><td className="size-column">{f.size}</td></tr>)}</tbody></table>{!visible.length&&<div className="empty-files"><Folder size={42} weight="light"/><h3>{query?'没有匹配的示例文件':'此位置暂无示例文件'}</h3><p>{query?'换个关键词，或清除搜索条件。':'打开“我的文件”体验摘要与文件整理。'}</p><button className="secondary-button" onClick={()=>goNav('files')}>返回资料目录</button></div>}</div>
 <footer className="file-footer"><span>{visible.length} 个项目{nav==='archive'?' · 示例归档':''}{undo&&<button className="text-button" onClick={undoPlan}>撤销上次整理</button>}</span><span>{org?<><Lock size={13}/>资料权限由单位管理</>:<><ShieldCheck size={13}/>仅使用选中的示例资料</>}</span></footer></div></div></section>}
 {aiOpen&&<aside className="assistant-window" aria-label="AI 助手"><header className="assistant-head"><strong className="ai-title">AI 助手</strong><span className="status-chip"><ShieldCheck size={14}/>{org?'内网模型':model==='local'?'本机处理':'云端模型'}</span><button className="icon-button" aria-label="AI 模型设置" onClick={()=>setModal('settings')}><DotsThree size={23}/></button></header><div className="assistant-body"><div className="prototype-chip">演示模式 · 未连接真实模型</div><div className="chat-user">{chat}</div><div className="chat-time">10月2日 10:24</div><div className="assistant-answer"><span className="ai-avatar"><Sparkle size={24} weight="fill"/></span><div className="answer-text">{busy?'正在生成示例摘要…':task==='organize'?'已准备文件整理方案。请先检查目标位置，再确认执行。':task==='done'?'示例文件已整理完成。你可以撤销本次操作，恢复原来的文件位置。':task==='search'?'搜索结果已显示在左侧。打开文件即可查看匹配的示例内容。':org?'根据你可访问的示例资料，已整理相关流程，并附上原文供你核对。':'我已整理所选资料的示例摘要，涵盖项目目标、主要任务、预算安排与下一步计划。'}</div></div>{notice&&<div className="notice" role="status">{notice}</div>}
 {task==='summary'&&<section className="summary-block"><h3>摘要要点</h3><ul className="summary-list">{summaries.map(f=><li key={f.id}><strong>{f.title}：</strong>{f.excerpt}</li>)}</ul><div className="references"><h3>参考文件</h3>{summaries.map(f=><button key={f.id} className="reference-button" onClick={()=>openSource(f)}><FileIcon file={f}/><span>{f.name}</span><CaretRight size={14}/></button>)}</div></section>}
 {task==='organize'&&<section className="summary-block"><h3>整理预览 · {selectedFiles.length} 个文件</h3>{selectedFiles.map(f=><div key={f.id} className="plan-item"><span>{f.name}</span><span><CaretRight size={12}/>项目归档 / {destinations[f.type]}</span></div>)}<p className="small-note">仅移动示例文件，不删除、不覆盖；可撤销上一次整理。</p></section>}
 {task==='done'&&<section className="summary-block"><h3><Check size={18}/>整理完成</h3><p>已归档到“项目归档”，可在左侧查看。</p>{undo&&<button className="secondary-button" onClick={undoPlan}><ArrowCounterClockwise size={16}/>撤销整理</button>}</section>}
 <div className="task-options"><button className="secondary-button" disabled={busy} onClick={generate}><FileText size={15}/>更新摘要</button><button className="secondary-button" onClick={organize} disabled={org}>{org?<Lock size={15}/>:<Folder size={15}/>}{org?'知识库只读':'整理文件'}</button></div></div><footer className="assistant-footer">{task==='organize'?<button className="primary-button" onClick={()=>setModal('plan')} disabled={!selectedFiles.length}>检查并确认整理</button>:<button className="primary-button" onClick={()=>setModal('summary')} disabled={!summaries.length||busy}><FileText size={18}/>预览摘要</button>}<form className="ai-composer" onSubmit={submitPrompt}><input value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="试试：找预算文件" aria-label="向 AI 助手描述任务"/><button type="submit" aria-label="发送任务" disabled={!prompt.trim()||busy}><ArrowUp size={18}/></button></form></footer></aside>}
 {!fileOpen&&!aiOpen&&<div className="desktop-empty"><button className="desktop-shortcut" onClick={()=>setFileOpen(true)}><Folder size={42} weight="fill"/>我的文件</button><button className="desktop-shortcut" onClick={()=>setAiOpen(true)}><Sparkle size={42} weight="fill"/>AI 助手</button></div>}</div>
 <footer className="taskbar"><div className="task-icons"><button className={'dock-button '+(launcher?'active':'')} aria-label="打开应用菜单" onClick={()=>setLauncher(!launcher)}><img className="brand-logo brand-logo-dock" src="/lantu-os-logo.png" alt=""/></button><span className="dock-divider"/>{[['文件',Folder,'#edae29'],['浏览器',Globe,'#0f9bb0'],['AI 助手',Sparkle,'#2563eb'],['日历',CalendarBlank,'#ec6555'],['系统设置',GearSix,'#65738a']].map(([name,Icon,color])=><button key={name} className={'dock-button '+(name==='文件'&&fileOpen?'active':'')} aria-label={name} onClick={()=>launch(name)}><Icon size={31} color={color} weight={name==='文件'?'fill':'duotone'}/></button>)}</div><div className="tray"><span className="tray-demo">原型演示</span><button aria-label="网络设置" onClick={()=>setModal('network')}><WifiHigh size={20}/></button><button aria-label="音量设置" onClick={()=>setModal('audio')}><SpeakerHigh size={20}/></button><button aria-label="电池与电源" onClick={()=>setModal('power')}><BatteryFull size={23}/>{pc.battery!==null&&<small>{pc.battery}%</small>}</button><span className="clock">{now.toLocaleDateString('zh-CN',{month:'long',day:'numeric'})} <strong>{now.toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit',hour12:false})}</strong></span></div></footer>
 {launcher&&<section className="launcher" aria-label="应用菜单"><div className="launcher-header"><span className="launcher-brand"><img className="brand-logo brand-logo-menu" src="/lantu-os-logo.png" alt=""/><strong>澜图 OS</strong></span><button className="icon-button" aria-label="关闭应用菜单" onClick={()=>setLauncher(false)}><X/></button></div><div className="launcher-grid">{[['文件',Folder],['AI 助手',Sparkle],['应用中心',SquaresFour],['浏览器',Globe],['日历',CalendarBlank],['系统设置',GearSix]].map(([label,Icon])=><button className="app-tile" key={label} onClick={()=>label==='应用中心'?(setModal('apps'),setLauncher(false)):launch(label)}><Icon size={28} weight="duotone"/>{label}</button>)}</div><p className="small-note">中文环境 · 普通用户桌面</p></section>}
 {toast&&<div className="toast" role="status"><Check size={17}/>{toast}</div>}
 {modal&&<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setModal(null);}}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="dialog-title" ref={modalRef}><header className="modal-header"><h2 id="dialog-title">{titles[modal]||modal.replace('app:','')}</h2><button className="icon-button" aria-label="关闭弹窗" onClick={()=>setModal(null)}><X size={21}/></button></header><div className="modal-body">
 {['browser','audio','network','power'].includes(modal)&&<PcFeatures page={modal} status={pc} setStatus={setPc} refresh={refreshPc} notify={flash}/>}
 {modal==='source'&&source&&<article className="source-document"><div className="doc-meta">{source.folder} · 示例资料</div><h2>{source.name.replace(/\.[^.]+$/,'')}</h2>{source.lines.map(([title,body],i)=><section className="document-section" key={title}><h3>§{i+1} {title}</h3><p>{body}</p></section>)}</article>}
 {modal==='summary'&&<><div className="notice"><ShieldCheck size={18}/>当前为预设示例摘要，未调用模型；可打开引用核对。</div><h2>{org?'办公设备使用摘要':'2026 年 Q4 工作摘要'}</h2>{summaries.map(f=><section className="document-section" key={f.id}><h3>{f.title}</h3><p>{f.excerpt}</p><button className="text-button" onClick={()=>openSource(f)}>查看来源：{f.name} · §1—§3<CaretRight size={13}/></button></section>)}<p className="small-note">正式版本将根据文档实际内容生成摘要，并定位至引用段落。</p></>}
 {modal==='plan'&&<><div className="notice">确认后只会改变本原型中的示例文件位置。</div><table className="plan-table"><thead><tr><th>文件与原位置</th><th>目标位置</th></tr></thead><tbody>{selectedFiles.map(f=><tr key={f.id}><td><strong>{f.name}</strong><small>{f.folder}</small></td><td>项目归档 / {destinations[f.type]}</td></tr>)}</tbody></table><p className="small-note">本次 {selectedFiles.length} 个文件，无同名冲突。保留文件名，不覆盖文件。原型仅支持撤销最近一次整理；刷新页面会重置演示。</p></>}
 {modal==='settings'&&<><div className="settings-row"><span><strong>工作空间</strong><small>{org?'单位配置 · 演示身份':'个人配置'}</small></span><span>{org?<><Buildings/>示例单位</>:<><User/>个人用户</>}</span></div><div className="settings-row"><label htmlFor="model"><strong>AI 模型位置</strong><small>{org?'此设置由单位管理员统一管理':'演示本地处理与云端服务的区别'}</small></label><select id="model" className="settings-select" disabled={org} value={model} onChange={e=>setModel(e.target.value)}>{org?<option value="intranet">单位内网模型</option>:<><option value="local">本机模型</option><option value="cloud">云端模型</option></>}</select></div>{org?<div className="notice"><Lock size={18}/>正式产品中，单位策略由身份和设备管理决定，用户不能通过切换视角绕过。</div>:model==='cloud'?<div className="warning">正式版本中，云端请求会发送选中的必要资料，并在发送前显示数据范围与服务商。此原型不发送任何文件。</div>:<div className="notice">本机模型需下载安装并满足硬件要求。当前未安装模型，结果为交互演示。</div>}<div className="settings-row"><span><strong>语言与输入</strong><small>{pc.native?'系统已配备 Fcitx5 拼音输入法':'Linux 版本配备 Fcitx5 拼音输入法'}</small></span><span>简体中文 · 拼音</span></div><div className="settings-row"><span><strong>资料范围</strong><small>本次仅包含左侧勾选的示例文件</small></span><span>{selected.length} 份资料</span></div><p className="small-note">{pc.native?'电脑基础设置已连接 Linux。文件与 AI 功能使用示例数据，尚未连接真实模型或单位管理服务。':'当前是浏览器预览；文件与 AI 使用示例数据，系统控制在 Linux 版本中启用。'}</p></>}
 {modal==='apps'&&<><p>首期应用目录规划</p><div className="app-grid">{[['文件',Folder],['AI 助手',Sparkle],['系统设置',GearSix]].map(([name,Icon])=><button className="app-tile" key={name} onClick={()=>{setModal(null);launch(name);}}><Icon size={30}/>{name}<small>可体验</small></button>)}</div><p className="small-note">办公软件、浏览器、聊天与会议软件的安装和兼容性，将在 Linux 真机阶段逐项验证。</p></>}
 {modal.startsWith('app:')&&<div className="app-placeholder"><Monitor size={44}/><h3>{modal.replace('app:','')} · 应用入口预览</h3><p>这个入口用于展示桌面应用组织方式。当前可体验文件管理、AI 摘要、文件整理与系统设置。</p><button className="secondary-button" onClick={()=>setModal('apps')}>查看可体验的应用</button></div>}
 </div><footer className="modal-footer">{modal==='plan'?<><button className="secondary-button" onClick={()=>setModal(null)}>取消</button><button className="primary-button" disabled={!selectedFiles.length} onClick={commitPlan}>确认整理 {selectedFiles.length} 个文件</button></>:<button className="secondary-button" onClick={()=>setModal(null)}>完成</button>}</footer></section></div>}
 </main>;
}
